"""
SQLite Database Models for AI Scalping Service
Stores all data needed for strategy analysis, learning, and self-improvement
"""

import sqlite3
from datetime import datetime, date
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass, field, asdict
from enum import Enum
import json
import threading


class TradeMode(Enum):
    """Trading execution mode"""
    PAPER = "paper"  # Simulated trades, no real money
    PRODUCTION = "production"  # Real trades with money


class TradeStatus(Enum):
    """Trade lifecycle status"""
    PENDING = "pending"
    ENTERED = "entered"
    PARTIAL_EXIT = "partial_exit"
    EXITED = "exited"
    CANCELLED = "cancelled"
    FAILED = "failed"


class SignalType(Enum):
    """Signal types for analysis"""
    MOMENTUM_ENTRY = "momentum_entry"
    MOMENTUM_EXIT = "momentum_exit"
    AI_OVERRIDE = "ai_override"
    STOP_LOSS = "stop_loss"
    TARGET_HIT = "target_hit"
    TIME_EXIT = "time_exit"
    CONSECUTIVE_TICK = "consecutive_tick"


@dataclass
class MarketTick:
    """Single market tick data"""
    id: Optional[int] = None
    timestamp: datetime = field(default_factory=datetime.now)
    instrument: str = ""
    symbol: str = ""
    ltp: float = 0.0
    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    volume: int = 0
    oi: int = 0
    bid: float = 0.0
    ask: float = 0.0
    bid_qty: int = 0
    ask_qty: int = 0


@dataclass
class MomentumSnapshot:
    """Momentum state at a point in time"""
    id: Optional[int] = None
    timestamp: datetime = field(default_factory=datetime.now)
    instrument: str = ""
    score: float = 50.0
    velocity: float = 0.0
    acceleration: float = 0.0
    phase: str = "DORMANT"
    consecutive_up: int = 0
    consecutive_down: int = 0
    streak_strength: float = 0.0
    volume_ratio: float = 1.0


@dataclass
class Signal:
    """Trading signal generated by the engine"""
    id: Optional[int] = None
    timestamp: datetime = field(default_factory=datetime.now)
    instrument: str = ""
    signal_type: str = ""
    direction: str = ""  # LONG or SHORT
    strength: float = 0.0
    momentum_score: float = 0.0
    ai_confidence: float = 0.0
    reason: str = ""
    was_executed: bool = False
    execution_result: str = ""


@dataclass
class PaperTrade:
    """Paper trade (simulated execution)"""
    id: Optional[int] = None
    trade_id: str = ""
    timestamp_entry: datetime = field(default_factory=datetime.now)
    timestamp_exit: Optional[datetime] = None
    instrument: str = ""
    option_type: str = ""  # CE or PE
    strike: float = 0.0
    entry_price: float = 0.0
    exit_price: Optional[float] = None
    quantity: int = 0
    lot_size: int = 0
    pnl: float = 0.0
    pnl_percent: float = 0.0
    status: str = "entered"
    entry_reason: str = ""
    exit_reason: str = ""
    momentum_at_entry: float = 0.0
    momentum_at_exit: float = 0.0
    ai_confidence_entry: float = 0.0
    duration_seconds: int = 0
    max_profit: float = 0.0
    max_loss: float = 0.0


@dataclass
class DailyStats:
    """Daily performance statistics"""
    id: Optional[int] = None
    date: date = field(default_factory=date.today)
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_pnl: float = 0.0
    max_drawdown: float = 0.0
    profit_factor: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    best_trade: float = 0.0
    worst_trade: float = 0.0
    total_signals: int = 0
    executed_signals: int = 0
    signal_accuracy: float = 0.0
    avg_momentum_at_entry: float = 0.0
    avg_ai_confidence: float = 0.0


@dataclass
class StrategyConfig:
    """Strategy configuration for tracking changes"""
    id: Optional[int] = None
    timestamp: datetime = field(default_factory=datetime.now)
    config_json: str = ""
    performance_before: float = 0.0
    performance_after: float = 0.0
    is_active: bool = True
    notes: str = ""


@dataclass
class LearningInsight:
    """AI-generated insights for improvement"""
    id: Optional[int] = None
    timestamp: datetime = field(default_factory=datetime.now)
    insight_type: str = ""  # signal_quality, momentum_accuracy, timing, etc.
    description: str = ""
    recommendation: str = ""
    confidence: float = 0.0
    implemented: bool = False
    result: str = ""


class ScalpingDatabase:
    """SQLite database manager for AI Scalping Service"""
    
    def __init__(self, db_path: str = None):
        if db_path is None:
            db_dir = Path(__file__).parent
            db_path = str(db_dir / "scalping_data.db")
        
        self.db_path = db_path
        self._local = threading.local()
        self._init_database()
    
    @property
    def conn(self) -> sqlite3.Connection:
        """Thread-local database connection"""
        if not hasattr(self._local, 'conn') or self._local.conn is None:
            self._local.conn = sqlite3.connect(self.db_path, check_same_thread=False)
            self._local.conn.row_factory = sqlite3.Row
        return self._local.conn
    
    def _init_database(self):
        """Initialize all database tables"""
        cursor = self.conn.cursor()
        
        # Trading mode table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS trading_mode (
                id INTEGER PRIMARY KEY,
                mode TEXT NOT NULL DEFAULT 'paper',
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_by TEXT DEFAULT 'system'
            )
        """)
        
        # Service state table - for persistent strategy enabled/disabled state
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS service_state (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Market ticks table - for historical analysis
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS market_ticks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TIMESTAMP NOT NULL,
                instrument TEXT NOT NULL,
                symbol TEXT,
                ltp REAL NOT NULL,
                open REAL,
                high REAL,
                low REAL,
                close REAL,
                volume INTEGER,
                oi INTEGER,
                bid REAL,
                ask REAL,
                bid_qty INTEGER,
                ask_qty INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Momentum snapshots - track momentum evolution
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS momentum_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TIMESTAMP NOT NULL,
                instrument TEXT NOT NULL,
                score REAL,
                velocity REAL,
                acceleration REAL,
                phase TEXT,
                consecutive_up INTEGER,
                consecutive_down INTEGER,
                streak_strength REAL,
                volume_ratio REAL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Signals table - all signals generated
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TIMESTAMP NOT NULL,
                instrument TEXT NOT NULL,
                signal_type TEXT NOT NULL,
                direction TEXT,
                strength REAL,
                momentum_score REAL,
                ai_confidence REAL,
                reason TEXT,
                was_executed INTEGER DEFAULT 0,
                execution_result TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Paper trades table - simulated trades
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS paper_trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                trade_id TEXT UNIQUE NOT NULL,
                timestamp_entry TIMESTAMP NOT NULL,
                timestamp_exit TIMESTAMP,
                instrument TEXT NOT NULL,
                option_type TEXT,
                strike REAL,
                entry_price REAL NOT NULL,
                exit_price REAL,
                quantity INTEGER NOT NULL,
                lot_size INTEGER,
                pnl REAL DEFAULT 0,
                pnl_percent REAL DEFAULT 0,
                status TEXT DEFAULT 'entered',
                entry_reason TEXT,
                exit_reason TEXT,
                momentum_at_entry REAL,
                momentum_at_exit REAL,
                ai_confidence_entry REAL,
                duration_seconds INTEGER,
                max_profit REAL DEFAULT 0,
                max_loss REAL DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Daily statistics - aggregated daily performance
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS daily_stats (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                date DATE UNIQUE NOT NULL,
                total_trades INTEGER DEFAULT 0,
                winning_trades INTEGER DEFAULT 0,
                losing_trades INTEGER DEFAULT 0,
                win_rate REAL DEFAULT 0,
                total_pnl REAL DEFAULT 0,
                max_drawdown REAL DEFAULT 0,
                profit_factor REAL DEFAULT 0,
                avg_win REAL DEFAULT 0,
                avg_loss REAL DEFAULT 0,
                best_trade REAL DEFAULT 0,
                worst_trade REAL DEFAULT 0,
                total_signals INTEGER DEFAULT 0,
                executed_signals INTEGER DEFAULT 0,
                signal_accuracy REAL DEFAULT 0,
                avg_momentum_at_entry REAL DEFAULT 0,
                avg_ai_confidence REAL DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Strategy configurations - track config changes
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS strategy_configs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                config_json TEXT NOT NULL,
                performance_before REAL DEFAULT 0,
                performance_after REAL DEFAULT 0,
                is_active INTEGER DEFAULT 1,
                notes TEXT
            )
        """)
        
        # Learning insights - AI-generated recommendations
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS learning_insights (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                insight_type TEXT NOT NULL,
                description TEXT NOT NULL,
                recommendation TEXT,
                confidence REAL DEFAULT 0,
                implemented INTEGER DEFAULT 0,
                result TEXT
            )
        """)
        
        # Option chain snapshots - for analysis
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS option_chain (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TIMESTAMP NOT NULL,
                instrument TEXT NOT NULL,
                expiry DATE NOT NULL,
                strike REAL NOT NULL,
                option_type TEXT NOT NULL,
                ltp REAL,
                iv REAL,
                delta REAL,
                gamma REAL,
                theta REAL,
                vega REAL,
                oi INTEGER,
                volume INTEGER,
                bid REAL,
                ask REAL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Performance metrics - for tracking improvement over time
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS performance_metrics (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                metric_name TEXT NOT NULL,
                metric_value REAL NOT NULL,
                period TEXT,
                notes TEXT
            )
        """)
        
        # Create indexes for faster queries
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_ticks_timestamp ON market_ticks(timestamp)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_ticks_instrument ON market_ticks(instrument)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_momentum_timestamp ON momentum_snapshots(timestamp)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_trades_status ON paper_trades(status)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_daily_date ON daily_stats(date)")
        
        # Initialize trading mode if not exists
        cursor.execute("SELECT COUNT(*) FROM trading_mode")
        if cursor.fetchone()[0] == 0:
            cursor.execute("INSERT INTO trading_mode (mode) VALUES ('paper')")
        
        self.conn.commit()
    
    # ==================== Trading Mode ====================
    
    def get_trading_mode(self) -> TradeMode:
        """Get current trading mode"""
        cursor = self.conn.cursor()
        cursor.execute("SELECT mode FROM trading_mode ORDER BY id DESC LIMIT 1")
        row = cursor.fetchone()
        return TradeMode(row['mode']) if row else TradeMode.PAPER
    
    def set_trading_mode(self, mode: TradeMode, updated_by: str = "api") -> bool:
        """Set trading mode (paper or production)"""
        cursor = self.conn.cursor()
        cursor.execute("""
            UPDATE trading_mode SET mode = ?, updated_at = ?, updated_by = ?
            WHERE id = (SELECT MAX(id) FROM trading_mode)
        """, (mode.value, datetime.now(), updated_by))
        self.conn.commit()
        return cursor.rowcount > 0
    
    # ==================== Market Ticks ====================
    
    def insert_tick(self, tick: MarketTick) -> int:
        """Insert a market tick"""
        cursor = self.conn.cursor()
        cursor.execute("""
            INSERT INTO market_ticks 
            (timestamp, instrument, symbol, ltp, open, high, low, close, volume, oi, bid, ask, bid_qty, ask_qty)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (tick.timestamp, tick.instrument, tick.symbol, tick.ltp, tick.open, 
              tick.high, tick.low, tick.close, tick.volume, tick.oi,
              tick.bid, tick.ask, tick.bid_qty, tick.ask_qty))
        self.conn.commit()
        return cursor.lastrowid
    
    def insert_ticks_batch(self, ticks: List[MarketTick]) -> int:
        """Insert multiple ticks efficiently"""
        cursor = self.conn.cursor()
        data = [(t.timestamp, t.instrument, t.symbol, t.ltp, t.open, t.high, t.low, 
                 t.close, t.volume, t.oi, t.bid, t.ask, t.bid_qty, t.ask_qty) for t in ticks]
        cursor.executemany("""
            INSERT INTO market_ticks 
            (timestamp, instrument, symbol, ltp, open, high, low, close, volume, oi, bid, ask, bid_qty, ask_qty)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, data)
        self.conn.commit()
        return len(data)
    
    def get_ticks(self, instrument: str, start: datetime, end: datetime) -> List[Dict]:
        """Get ticks for an instrument in a time range"""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM market_ticks 
            WHERE instrument = ? AND timestamp BETWEEN ? AND ?
            ORDER BY timestamp
        """, (instrument, start, end))
        return [dict(row) for row in cursor.fetchall()]
    
    # ==================== Momentum Snapshots ====================
    
    def insert_momentum(self, momentum: MomentumSnapshot) -> int:
        """Insert momentum snapshot"""
        cursor = self.conn.cursor()
        cursor.execute("""
            INSERT INTO momentum_snapshots 
            (timestamp, instrument, score, velocity, acceleration, phase, 
             consecutive_up, consecutive_down, streak_strength, volume_ratio)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (momentum.timestamp, momentum.instrument, momentum.score, momentum.velocity,
              momentum.acceleration, momentum.phase, momentum.consecutive_up,
              momentum.consecutive_down, momentum.streak_strength, momentum.volume_ratio))
        self.conn.commit()
        return cursor.lastrowid
    
    def get_momentum_history(self, instrument: str, hours: int = 24) -> List[Dict]:
        """Get momentum history for analysis"""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM momentum_snapshots 
            WHERE instrument = ? AND timestamp >= datetime('now', ? || ' hours')
            ORDER BY timestamp
        """, (instrument, -hours))
        return [dict(row) for row in cursor.fetchall()]
    
    # ==================== Signals ====================
    
    def insert_signal(self, signal: Signal) -> int:
        """Insert a trading signal"""
        cursor = self.conn.cursor()
        cursor.execute("""
            INSERT INTO signals 
            (timestamp, instrument, signal_type, direction, strength, momentum_score, 
             ai_confidence, reason, was_executed, execution_result)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (signal.timestamp, signal.instrument, signal.signal_type, signal.direction,
              signal.strength, signal.momentum_score, signal.ai_confidence, signal.reason,
              1 if signal.was_executed else 0, signal.execution_result))
        self.conn.commit()
        return cursor.lastrowid
    
    def update_signal_execution(self, signal_id: int, was_executed: bool, result: str):
        """Update signal execution status"""
        cursor = self.conn.cursor()
        cursor.execute("""
            UPDATE signals SET was_executed = ?, execution_result = ? WHERE id = ?
        """, (1 if was_executed else 0, result, signal_id))
        self.conn.commit()
    
    def get_signals_by_date(self, target_date: date) -> List[Dict]:
        """Get all signals for a date"""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM signals 
            WHERE DATE(timestamp) = ?
            ORDER BY timestamp
        """, (target_date,))
        return [dict(row) for row in cursor.fetchall()]
    
    # ==================== Paper Trades ====================
    
    def insert_paper_trade(self, trade: PaperTrade) -> int:
        """Insert a paper trade"""
        cursor = self.conn.cursor()
        cursor.execute("""
            INSERT INTO paper_trades 
            (trade_id, timestamp_entry, instrument, option_type, strike, entry_price, 
             quantity, lot_size, status, entry_reason, momentum_at_entry, ai_confidence_entry)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (trade.trade_id, trade.timestamp_entry, trade.instrument, trade.option_type,
              trade.strike, trade.entry_price, trade.quantity, trade.lot_size,
              trade.status, trade.entry_reason, trade.momentum_at_entry, trade.ai_confidence_entry))
        self.conn.commit()
        return cursor.lastrowid
    
    def update_paper_trade_exit(self, trade_id: str, exit_price: float, exit_reason: str,
                                 momentum_at_exit: float, pnl: float, pnl_percent: float):
        """Update paper trade with exit details"""
        cursor = self.conn.cursor()
        now = datetime.now()
        
        # Get entry time to calculate duration
        cursor.execute("SELECT timestamp_entry, entry_price FROM paper_trades WHERE trade_id = ?", (trade_id,))
        row = cursor.fetchone()
        if row:
            entry_time = datetime.fromisoformat(row['timestamp_entry']) if isinstance(row['timestamp_entry'], str) else row['timestamp_entry']
            duration = int((now - entry_time).total_seconds())
        else:
            duration = 0
        
        cursor.execute("""
            UPDATE paper_trades SET 
                timestamp_exit = ?, exit_price = ?, exit_reason = ?, momentum_at_exit = ?,
                pnl = ?, pnl_percent = ?, status = 'exited', duration_seconds = ?
            WHERE trade_id = ?
        """, (now, exit_price, exit_reason, momentum_at_exit, pnl, pnl_percent, duration, trade_id))
        self.conn.commit()
    
    def update_paper_trade_extremes(self, trade_id: str, current_pnl: float):
        """Update max profit/loss for a trade"""
        cursor = self.conn.cursor()
        cursor.execute("SELECT max_profit, max_loss FROM paper_trades WHERE trade_id = ?", (trade_id,))
        row = cursor.fetchone()
        if row:
            max_profit = max(row['max_profit'], current_pnl)
            max_loss = min(row['max_loss'], current_pnl)
            cursor.execute("""
                UPDATE paper_trades SET max_profit = ?, max_loss = ? WHERE trade_id = ?
            """, (max_profit, max_loss, trade_id))
            self.conn.commit()
    
    def get_open_paper_trades(self) -> List[Dict]:
        """Get all open paper trades"""
        cursor = self.conn.cursor()
        cursor.execute("SELECT * FROM paper_trades WHERE status = 'entered'")
        return [dict(row) for row in cursor.fetchall()]
    
    def get_paper_trades_by_date(self, target_date: date) -> List[Dict]:
        """Get all paper trades for a date"""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM paper_trades WHERE DATE(timestamp_entry) = ?
            ORDER BY timestamp_entry
        """, (target_date,))
        return [dict(row) for row in cursor.fetchall()]
    
    def get_recent_paper_trades(self, limit: int = 100) -> List[Dict]:
        """Get recent paper trades"""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM paper_trades ORDER BY timestamp_entry DESC LIMIT ?
        """, (limit,))
        return [dict(row) for row in cursor.fetchall()]
    
    # ==================== Daily Stats ====================
    
    def update_daily_stats(self, target_date: date = None):
        """Calculate and update daily statistics"""
        if target_date is None:
            target_date = date.today()
        
        cursor = self.conn.cursor()
        
        # Get all trades for the date
        cursor.execute("""
            SELECT * FROM paper_trades 
            WHERE DATE(timestamp_entry) = ? AND status = 'exited'
        """, (target_date,))
        trades = cursor.fetchall()
        
        if not trades:
            return
        
        # Calculate statistics
        total_trades = len(trades)
        winning_trades = sum(1 for t in trades if t['pnl'] > 0)
        losing_trades = sum(1 for t in trades if t['pnl'] <= 0)
        win_rate = winning_trades / total_trades * 100 if total_trades > 0 else 0
        
        total_pnl = sum(t['pnl'] for t in trades)
        
        wins = [t['pnl'] for t in trades if t['pnl'] > 0]
        losses = [abs(t['pnl']) for t in trades if t['pnl'] < 0]
        
        avg_win = sum(wins) / len(wins) if wins else 0
        avg_loss = sum(losses) / len(losses) if losses else 0
        profit_factor = sum(wins) / sum(losses) if losses and sum(losses) > 0 else 999
        
        best_trade = max(t['pnl'] for t in trades)
        worst_trade = min(t['pnl'] for t in trades)
        
        avg_momentum = sum(t['momentum_at_entry'] for t in trades) / total_trades
        avg_confidence = sum(t['ai_confidence_entry'] or 0 for t in trades) / total_trades
        
        # Get signals
        cursor.execute("SELECT COUNT(*) FROM signals WHERE DATE(timestamp) = ?", (target_date,))
        total_signals = cursor.fetchone()[0]
        
        cursor.execute("SELECT COUNT(*) FROM signals WHERE DATE(timestamp) = ? AND was_executed = 1", (target_date,))
        executed_signals = cursor.fetchone()[0]
        
        # Upsert daily stats
        cursor.execute("""
            INSERT INTO daily_stats 
            (date, total_trades, winning_trades, losing_trades, win_rate, total_pnl, 
             profit_factor, avg_win, avg_loss, best_trade, worst_trade, 
             total_signals, executed_signals, avg_momentum_at_entry, avg_ai_confidence, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(date) DO UPDATE SET
                total_trades = excluded.total_trades,
                winning_trades = excluded.winning_trades,
                losing_trades = excluded.losing_trades,
                win_rate = excluded.win_rate,
                total_pnl = excluded.total_pnl,
                profit_factor = excluded.profit_factor,
                avg_win = excluded.avg_win,
                avg_loss = excluded.avg_loss,
                best_trade = excluded.best_trade,
                worst_trade = excluded.worst_trade,
                total_signals = excluded.total_signals,
                executed_signals = excluded.executed_signals,
                avg_momentum_at_entry = excluded.avg_momentum_at_entry,
                avg_ai_confidence = excluded.avg_ai_confidence,
                updated_at = excluded.updated_at
        """, (target_date, total_trades, winning_trades, losing_trades, win_rate, total_pnl,
              profit_factor, avg_win, avg_loss, best_trade, worst_trade,
              total_signals, executed_signals, avg_momentum, avg_confidence, datetime.now()))
        self.conn.commit()
    
    def get_daily_stats(self, days: int = 30) -> List[Dict]:
        """Get daily statistics for the last N days"""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM daily_stats 
            ORDER BY date DESC LIMIT ?
        """, (days,))
        return [dict(row) for row in cursor.fetchall()]
    
    # ==================== Strategy Configs ====================
    
    def save_strategy_config(self, config: Dict, notes: str = "") -> int:
        """Save a strategy configuration"""
        cursor = self.conn.cursor()
        # Deactivate previous configs
        cursor.execute("UPDATE strategy_configs SET is_active = 0")
        
        cursor.execute("""
            INSERT INTO strategy_configs (config_json, is_active, notes)
            VALUES (?, 1, ?)
        """, (json.dumps(config), notes))
        self.conn.commit()
        return cursor.lastrowid
    
    def get_active_config(self) -> Optional[Dict]:
        """Get the active strategy configuration"""
        cursor = self.conn.cursor()
        cursor.execute("SELECT * FROM strategy_configs WHERE is_active = 1 ORDER BY id DESC LIMIT 1")
        row = cursor.fetchone()
        if row:
            result = dict(row)
            result['config'] = json.loads(result['config_json'])
            return result
        return None
    
    # ==================== Learning Insights ====================
    
    def add_insight(self, insight: LearningInsight) -> int:
        """Add a learning insight"""
        cursor = self.conn.cursor()
        cursor.execute("""
            INSERT INTO learning_insights 
            (insight_type, description, recommendation, confidence)
            VALUES (?, ?, ?, ?)
        """, (insight.insight_type, insight.description, insight.recommendation, insight.confidence))
        self.conn.commit()
        return cursor.lastrowid
    
    def get_pending_insights(self) -> List[Dict]:
        """Get insights that haven't been implemented yet"""
        cursor = self.conn.cursor()
        cursor.execute("SELECT * FROM learning_insights WHERE implemented = 0 ORDER BY confidence DESC")
        return [dict(row) for row in cursor.fetchall()]
    
    def mark_insight_implemented(self, insight_id: int, result: str):
        """Mark an insight as implemented with result"""
        cursor = self.conn.cursor()
        cursor.execute("""
            UPDATE learning_insights SET implemented = 1, result = ? WHERE id = ?
        """, (result, insight_id))
        self.conn.commit()
    
    # ==================== Analysis Queries ====================
    
    def get_win_rate_by_momentum_range(self) -> List[Dict]:
        """Analyze win rate by momentum score ranges"""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT 
                CASE 
                    WHEN momentum_at_entry < 60 THEN '50-60'
                    WHEN momentum_at_entry < 70 THEN '60-70'
                    WHEN momentum_at_entry < 80 THEN '70-80'
                    WHEN momentum_at_entry < 90 THEN '80-90'
                    ELSE '90-100'
                END as momentum_range,
                COUNT(*) as total_trades,
                SUM(CASE WHEN pnl > 0 THEN 1 ELSE 0 END) as wins,
                ROUND(SUM(CASE WHEN pnl > 0 THEN 1.0 ELSE 0 END) / COUNT(*) * 100, 2) as win_rate,
                ROUND(AVG(pnl), 2) as avg_pnl
            FROM paper_trades 
            WHERE status = 'exited'
            GROUP BY momentum_range
            ORDER BY momentum_range
        """)
        return [dict(row) for row in cursor.fetchall()]
    
    def get_best_performing_instruments(self) -> List[Dict]:
        """Get instruments ranked by performance"""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT 
                instrument,
                COUNT(*) as total_trades,
                SUM(CASE WHEN pnl > 0 THEN 1 ELSE 0 END) as wins,
                ROUND(SUM(CASE WHEN pnl > 0 THEN 1.0 ELSE 0 END) / COUNT(*) * 100, 2) as win_rate,
                ROUND(SUM(pnl), 2) as total_pnl,
                ROUND(AVG(pnl), 2) as avg_pnl
            FROM paper_trades 
            WHERE status = 'exited'
            GROUP BY instrument
            ORDER BY win_rate DESC
        """)
        return [dict(row) for row in cursor.fetchall()]
    
    def get_optimal_entry_conditions(self) -> Dict:
        """Analyze what entry conditions lead to best outcomes"""
        cursor = self.conn.cursor()
        
        # Best momentum score range
        cursor.execute("""
            SELECT 
                ROUND(momentum_at_entry / 5) * 5 as momentum_bucket,
                ROUND(AVG(pnl), 2) as avg_pnl,
                COUNT(*) as trades
            FROM paper_trades WHERE status = 'exited'
            GROUP BY momentum_bucket
            ORDER BY avg_pnl DESC
            LIMIT 1
        """)
        best_momentum = cursor.fetchone()
        
        # Best time of day
        cursor.execute("""
            SELECT 
                strftime('%H', timestamp_entry) as hour,
                ROUND(AVG(pnl), 2) as avg_pnl,
                COUNT(*) as trades
            FROM paper_trades WHERE status = 'exited'
            GROUP BY hour
            ORDER BY avg_pnl DESC
            LIMIT 1
        """)
        best_hour = cursor.fetchone()
        
        return {
            'best_momentum_range': dict(best_momentum) if best_momentum else None,
            'best_trading_hour': dict(best_hour) if best_hour else None
        }
    
    def get_analysis_summary(self) -> Dict:
        """Get comprehensive analysis summary for Copilot"""
        cursor = self.conn.cursor()
        
        summary = {}
        
        # Overall stats
        cursor.execute("""
            SELECT 
                COUNT(*) as total_trades,
                SUM(CASE WHEN pnl > 0 THEN 1 ELSE 0 END) as wins,
                ROUND(SUM(CASE WHEN pnl > 0 THEN 1.0 ELSE 0 END) / NULLIF(COUNT(*), 0) * 100, 2) as win_rate,
                ROUND(SUM(pnl), 2) as total_pnl,
                ROUND(AVG(pnl), 2) as avg_pnl,
                ROUND(AVG(duration_seconds), 0) as avg_duration_sec
            FROM paper_trades WHERE status = 'exited'
        """)
        summary['overall'] = dict(cursor.fetchone())
        
        # By instrument
        summary['by_instrument'] = self.get_best_performing_instruments()
        
        # By momentum
        summary['by_momentum'] = self.get_win_rate_by_momentum_range()
        
        # Recent performance trend
        cursor.execute("""
            SELECT 
                DATE(timestamp_entry) as trade_date,
                COUNT(*) as trades,
                ROUND(SUM(CASE WHEN pnl > 0 THEN 1.0 ELSE 0 END) / COUNT(*) * 100, 2) as win_rate,
                ROUND(SUM(pnl), 2) as pnl
            FROM paper_trades 
            WHERE status = 'exited' AND timestamp_entry >= date('now', '-7 days')
            GROUP BY trade_date
            ORDER BY trade_date
        """)
        summary['recent_trend'] = [dict(row) for row in cursor.fetchall()]
        
        # Optimal conditions
        summary['optimal_conditions'] = self.get_optimal_entry_conditions()
        
        return summary
    
    def cleanup_old_data(self, days_to_keep: int = 90):
        """Clean up old tick data to manage database size"""
        cursor = self.conn.cursor()
        cursor.execute("""
            DELETE FROM market_ticks WHERE timestamp < date('now', ? || ' days')
        """, (-days_to_keep,))
        cursor.execute("""
            DELETE FROM momentum_snapshots WHERE timestamp < date('now', ? || ' days')
        """, (-days_to_keep,))
        self.conn.commit()
        return cursor.rowcount


# Global database instance
_db_instance = None

def get_database() -> ScalpingDatabase:
    """Get the global database instance"""
    global _db_instance
    if _db_instance is None:
        _db_instance = ScalpingDatabase()
    return _db_instance
